RENDERER_DIR := renderer
RENDERER_SRC :=

RENDERER_SRC += \
	$(RENDERER_DIR)/Camera.cpp \
	$(RENDERER_DIR)/Object.cpp \
	$(RENDERER_DIR)/Renderer.cpp \
	$(RENDERER_DIR)/Render_OpenGl.cpp \
	$(RENDERER_DIR)/Scene.cpp